# Generated by Django 5.0.2 on 2024-02-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_library_author_name_library_book_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myarchive',
            name='converted',
            field=models.FileField(blank=True, null=True, upload_to='upload/'),
        ),
    ]
